---
- name: Uninstall old versions
  become: true
  apt:
    pkg:
    - docker
    - docker-engine
    - docker.io
    - containerd
    - runc
    state: absent

- name: Install dependencies
  become: true
  apt:
    pkg:
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    state: present
    update_cache: true

- name: Install Docker offical GPG key
  become: true
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present

- name: Add docker repository into sources list
  become: true
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable"
    state: present
    filename: docker

- name: Install docker
  become: true
  apt:
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose-plugin
    state: present
    update_cache: true

